/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : string,
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export interface QuoteRequest {
  'id' : bigint,
  'serviceType' : string,
  'name' : string,
  'isRead' : boolean,
  'attachedFile' : [] | [ExternalBlob],
  'responseTimestamp' : [] | [Time],
  'response' : [] | [string],
  'timestamp' : Time,
  'phoneNumber' : string,
  'projectDetails' : string,
}
export interface Review {
  'id' : bigint,
  'reviewText' : string,
  'reviewerName' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'icon' : string,
  'description' : string,
  'timestamp' : Time,
}
export interface SiteSettings {
  'websiteDescription' : string,
  'tagline' : string,
  'websiteUrl' : string,
  'heroText' : string,
  'whatsappNumber' : string,
  'address' : string,
  'aboutText' : string,
  'companyName' : string,
  'phoneNumber' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitorLog {
  'name' : string,
  'mobileNumber' : string,
  'timestamp' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminAddReview' : ActorMethod<[string, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGalleryItem' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'createService' : ActorMethod<[string, string, string], undefined>,
  'deleteGalleryItem' : ActorMethod<[string], undefined>,
  'deleteQuoteRequest' : ActorMethod<[bigint], undefined>,
  'deleteReview' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllQuoteRequests' : ActorMethod<[], Array<QuoteRequest>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGalleryItem' : ActorMethod<[string], GalleryItem>,
  'getQuoteCountByPhoneNumber' : ActorMethod<[string], bigint>,
  'getQuoteResponseByPhoneNumber' : ActorMethod<[string], Array<QuoteRequest>>,
  'getService' : ActorMethod<[bigint], Service>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUnreadQuoteCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorLogs' : ActorMethod<[], Array<VisitorLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logVisit' : ActorMethod<[string, string], undefined>,
  'markAllQuotesAsRead' : ActorMethod<[], undefined>,
  'respondToQuoteRequest' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuoteRequest' : ActorMethod<
    [string, string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'submitReview' : ActorMethod<[string, bigint, string], undefined>,
  'updateGalleryItem' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'updateReview' : ActorMethod<[bigint, string, bigint, string], undefined>,
  'updateService' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];