/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const Time = IDL.Int;
export const QuoteRequest = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'isRead' : IDL.Bool,
  'attachedFile' : IDL.Opt(ExternalBlob),
  'responseTimestamp' : IDL.Opt(Time),
  'response' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
  'projectDetails' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SiteSettings = IDL.Record({
  'websiteDescription' : IDL.Text,
  'tagline' : IDL.Text,
  'websiteUrl' : IDL.Text,
  'heroText' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'address' : IDL.Text,
  'aboutText' : IDL.Text,
  'companyName' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const VisitorLog = IDL.Record({
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminAddReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'createService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
  'deleteQuoteRequest' : IDL.Func([IDL.Nat], [], []),
  'deleteReview' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryItem' : IDL.Func([IDL.Text], [GalleryItem], ['query']),
  'getQuoteCountByPhoneNumber' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getQuoteResponseByPhoneNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUnreadQuoteCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorLogs' : IDL.Func([], [IDL.Vec(VisitorLog)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logVisit' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'markAllQuotesAsRead' : IDL.Func([], [], []),
  'respondToQuoteRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuoteRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'updateReview' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Time = IDL.Int;
  const QuoteRequest = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'isRead' : IDL.Bool,
    'attachedFile' : IDL.Opt(ExternalBlob),
    'responseTimestamp' : IDL.Opt(Time),
    'response' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
    'projectDetails' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SiteSettings = IDL.Record({
    'websiteDescription' : IDL.Text,
    'tagline' : IDL.Text,
    'websiteUrl' : IDL.Text,
    'heroText' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'address' : IDL.Text,
    'aboutText' : IDL.Text,
    'companyName' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const VisitorLog = IDL.Record({
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminAddReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'createService' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Text], [], []),
    'deleteQuoteRequest' : IDL.Func([IDL.Nat], [], []),
    'deleteReview' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllQuoteRequests' : IDL.Func([], [IDL.Vec(QuoteRequest)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryItem' : IDL.Func([IDL.Text], [GalleryItem], ['query']),
    'getQuoteCountByPhoneNumber' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getQuoteResponseByPhoneNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUnreadQuoteCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorLogs' : IDL.Func([], [IDL.Vec(VisitorLog)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logVisit' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'markAllQuotesAsRead' : IDL.Func([], [], []),
    'respondToQuoteRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuoteRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'updateReview' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };